add_newline = false
continuation_prompt = "[â–¸â–¹ ](dimmed white)"

format = """
[â–‘â–’â–“](fg:#3F6375)\
$os\
$username\
[î‚´ ](fg:#3F6375)\
$directory\
$git_branch\
$git_status\
$fill\
$netns\
\n$cmd_duration$sudo$character"""

right_format = """
$package\
$nodejs\
$php\
$rust\
$c\
$cpp\
$cmake\
"""

[fill]
symbol = ' '

[os]
format = "[ $symbol]($style)"
style = "bg:#3F6375 bold blue"
disabled = false

[username]
format = '[$user]($style)'
style_user = "bg:#3F6375 fg:#ECF2ED italic underline"
style_root = ""
show_always = true
disabled = false

[directory]
format = '[on](bold blue)[$symbol $path]($style)[$read_only]($read_only_style)'
style = "italic dimmed white"
home_symbol = "ó±‚µ "
truncation_symbol = "ó°‰‹ "
read_only = " ó°‰ "
truncation_length = 3
use_os_path_sep = true
repo_root_style = 'italic bright-blue'
repo_root_format = '[on](bold blue)[ $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'

[netns]
format = '[$symbol $name]($style)'
style = 'bold cyan'
symbol = 'ó°–© '

[cmd_duration]
format = "[ â—„ $duration ](italic white)"

[sudo]
format = "[ $symbol]($style)"
style = 'bold purple'
symbol = 'ï‹'
disabled = false

[character]
format = " $symbol "
success_symbol = '[_\$](italic green)'
error_symbol = '[_!](italic red)'
vimcmd_symbol = "[_â¯ ](italic dimmed green)"


[git_branch]
format = " â€” $symbol [$branch(:$remote_branch)]($style) "
style = "italic bright-green"
symbol = "[îœ¥](bold italic bright-green)"
truncation_symbol = "â‹¯"
truncation_length = 11
ignore_branches = []
only_attached = true

[git_metrics]
format = '([â–´$added]($added_style))([â–¿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
format = '[\[$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed\]]($style)'
style = "bold italic bright-blue"
ahead = "[ï‚ª (bold white)](italic green)"
behind = "[ï‚« (bold white)â”‚](italic red)"
staged = "[î¸™ [$count](bold white)â”‚](italic bright-cyan)"
modified = "[ï‘™ ](italic yellow)"
untracked = "[ó°‘ ](italic bright-yellow)"
renamed = "[ï€Ÿ ](italic bright-blue)"
deleted = "[ó°†´](italic red)"
conflicted = "[î™ ](italic bright-magenta)"
diverged = "[â—‡ â–´â”¤[${ahead_count}](regular white)â”‚â–¿â”¤[${behind_count}](regular white)â”‚](italic bright-magenta)"
stashed = "[â—ƒâ—ˆ](italic white)"

[package]
format = "[pkg](italic dimmed) [$symbol$version]($style)"
version_format = "v${raw}"
symbol = "ó°— "
style = "dimmed yellow bold"
display_private = true

[nodejs]
format = " [via](none) [node](italic bright-green) [îœ˜ ($version(:$engines_version))](bold bright-green) "
version_format = "v${raw}"
detect_files = ["package-lock.json", "yarn.lock", "package.json"]
detect_folders = ["node_modules"]
detect_extensions = []

[php]
format = " [via](none) [php](italic dimmed purple) [î˜ˆ ($version)](bold dimmed purple) "
version_format = "v${raw}"
detect_files = ["composer.json"]
detect_folders = ["node_modules"]
detect_extensions = ["php"]

[rust]
format = " [via](none) [rust](italic $style) [î¨ ($version)]($style) "
version_format = "v${raw}"
style = "bold red"
detect_files = ["Cargo.toml"]
detect_folders = []
detect_extensions = ["rs"]

[c]
format = " [via](none) [c](italic $style) [î± ($version(-$name))]($style) "
version_format = "v${raw}"
style = "bold 149"
detect_files = []
detect_folders = []
detect_extensions = ["c", "h"]
commands = [ [ 'cc', '--version' ], [ 'gcc', '--version' ], [ 'clang', '--version' ] ]

[cpp]
format = " [via](none) [cpp](italic $style) [î˜ ($version(-$name))]($style) "
version_format = "v${raw}"
style = "bold 149"
detect_files = []
detect_folders = []
detect_extensions = ['cpp', 'cc', 'cxx', 'c++', 'hpp', 'hh', 'hxx', 'h++', 'tcc']
commands = [ [ 'c++', '--version' ], [ 'g++', '--version' ], [ 'clang++', '--version' ] ]

[cmake]
format = "[with](none) [CMake](italic $style) [î” ($version)]($style) "
version_format = "v${raw}"
style = "bold dimmed red"
detect_files = ['CMakeLists.txt', 'CMakeCache.txt']
detect_folders = []
detect_extensions = []




[os.symbols]
Alpine = "ğŸ”ï¸ "
Arch = "îœ² "
Artix = "ğŸ—ï¸ "
CachyOS = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
DragonFly = "ğŸ‰ "
EndeavourOS = "ğŸš€ "
Fedora = "ğŸ© "
FreeBSD = "ğŸ˜ˆ "
Garuda = "ğŸ¦… "
Gentoo = "ğŸ—œï¸ "
Kali = "ğŸ‰ "
Linux = "ğŸ§ "
Macos = "ğŸ "
Manjaro = "ğŸ¥­ "
Mint = "ğŸŒ¿ "
NetBSD = "ğŸš© "
NixOS = "â„ï¸ "
Nobara = "ğŸ© "
OpenBSD = "ğŸ¡ "
openSUSE = "ğŸ¦ "
Pop = "ğŸ­ "
Raspbian = "ğŸ“ "
Redhat = "ğŸ© "
RedHatEnterprise = "ğŸ© "
Redox = "ğŸ§ª "
Solus = "â›µ "
SUSE = "ğŸ¦ "
Ubuntu = "ğŸ¯ "
Unknown = "â“ "
Void = "îŠ™  "
Windows = "ğŸªŸ "